Add mutli-set elements (`Þ∨` - difference, `Þ∩` - intersection, `Þ∪` - union, `Þ⊍` - xor)
Vyxal/Vyxal pull request #1101
Opened 2022-06-14 13:00 UTC by Lyxal

Closes #1066

2022-06-14 13:00 UTC, Lyxal commented
Tested against the results of Jelly.

2022-06-14 19:49 UTC, cgccuser requested changes

2022-06-14 19:49 UTC, cgccuser commented on vyxal/LazyList.py
> +    def remove(self, value):
Weren't we were planning on making `LazyList`s immutable? This mutates the generated list.

2022-06-14 19:53 UTC, chunkybanana requested changes

2022-06-14 19:53 UTC, chunkybanana commented on vyxal/elements.py
> +    return res
This doesn't seem to handle the multiset part - it looks like passing `[1, 1, 1]` and `[1]` will return `[1, 1, 1]` where it should return `[1]`.

2022-06-15 11:51 UTC, cgccuser approved these changes

2022-06-15 12:23 UTC, SE-Nitro approved these changes
I don't want to merge it yet, I might have missed something

2022-06-16 07:28 UTC, chunkybanana approved these changes

2022-06-16 07:28 UTC, merged