Make `⌊` account for decimals and negatives
Vyxal/Vyxal pull request #1198
Opened 2022-06-28 05:28 UTC by Lyxal

Goes towards closing #1164

2022-06-28 13:07 UTC, cgccuser commented on vyxal/elements.py
> +    def vy_floor_str_helper(item):
Wanna move this to helpers.py?

2022-06-28 13:09 UTC, cgccuser requested changes

2022-06-28 13:09 UTC, cgccuser commented on vyxal/elements.py
> +            elif char == "." and temp.count(".") == 0:
```suggestion
            elif char == "." and "." not in temp:
```

2022-06-28 13:09 UTC, cgccuser commented on vyxal/elements.py
> +                continue
```suggestion
```
No need to continue if you're already at the end.

2022-06-28 13:09 UTC, cgccuser commented on vyxal/elements.py
> +            elif char == "." and temp.count(".") == 0:
Might want to make sure you don't get a string like `-.` by adding a zero.

2022-07-03 19:06 UTC, cgccuser approved these changes

2022-07-03 19:09 UTC, Steffan153 approved these changes

2022-07-03 19:10 UTC, merged