Make Ǒ check for 0 and 1
Vyxal/Vyxal pull request #1245
Opened 2022-07-03 19:10 UTC by cgccuser

Closes #1244

For `lhs == 0`, returns 0. For `rhs == 0`, returns `math.inf`. For `abs(rhs) == 1`, returns `abs(lhs)`.

2022-07-03 19:18 UTC, Steffan153 requested changes
We don't use `math.inf` in Vyxal. It complicates things, so we replace it with `0`. If `inf` is ever encountered, it's a bug

2022-07-03 19:35 UTC, cgccuser commented on vyxal/elements.py
> +            return math.inf
```suggestion
        if lhs == 0 or rhs == 0:
            return 0
```

2022-07-03 19:43 UTC, chunkybanana approved these changes

2022-07-04 23:20 UTC, Steffan153 approved these changes
why is this still draft?

2022-07-04 23:30 UTC, merged