fix while loops
Vyxal/Vyxal pull request #1325
Opened 2022-07-16 03:18 UTC by Steffan153

Closes #1324

2022-07-16 04:38 UTC, chunkybanana approved these changes
Huh.

2022-07-16 04:39 UTC, chunkybanana requested changes

2022-07-16 04:39 UTC, chunkybanana commented on vyxal/transpile.py
> +            + indent_str("temp_len = len(ctx.context_values)", indent)
Nested while loops may break this

2022-07-16 12:56 UTC, Lyxal commented
Why not just pop the second context item it pushes? Or why not remove one of the context items being pushed?

2022-07-16 18:01 UTC, Steffan153 commented
> Why not just pop the second context item it pushes? Or why not remove one of the context items being pushed?

The condition being pushed was not needed, so I removed that. The rest of the code was because if `break` is used, then the context var is never popped.

2022-07-16 18:06 UTC, Steffan153 commented on vyxal/transpile.py
> +            + indent_str("temp_len = len(ctx.context_values)", indent)
Good catch, fixed.

2022-07-16 20:52 UTC, chunkybanana approved these changes
LGTM

2022-07-17 00:40 UTC, Lyxal approved these changes

2022-07-17 00:40 UTC, merged