Make `Ḣ` rangify
Vyxal/Vyxal pull request #1400
Opened 2022-08-13 11:17 UTC by Lyxal

Closes #1388

2022-08-13 11:17 UTC, Lyxal commented
Item number 1400 lol

2022-08-13 17:48 UTC, Steffan153 approved these changes

2022-08-15 14:35 UTC, cgccuser requested changes

2022-08-15 14:35 UTC, cgccuser commented on vyxal/elements.py
>      (num) -> Remove first digit or do nothing if <1"""
```suggestion
    (num) -> range(2, a + 1)"""
```

2022-08-15 14:35 UTC, cgccuser approved these changes

2022-08-15 14:36 UTC, merged