Add sugar trigraphs for real
Vyxal/Vyxal pull request #1666
Opened 2023-03-09 13:05 UTC by Lyxal

2023-03-09 13:31 UTC, Lyxal commented
At some stage, this needs to automatically print out what the converted program is if it uses sugar trigraphs. That can probably go in the apply section with a boolean set to true if a sugar trigraph is ever processed

2023-03-09 13:40 UTC, Lyxal commented
Also as a general naming rule thing:

- `#.<letter>` is the updot version of that letter if it exists
- `#,<letter>` is the downdot version of that letter if it exists
- `#^<letter>` is a superscript version of a letter if it exists
- `#.<symbol>` is what one would expect a trigraph to logically turn into
- `#,<symbol>` is what one would expect a trigraph to aesthetically turn into. Alternatively, if it has an underbar, use that.
`#^<symbol>` is superscript version if it exists. Otherwise, it's a sort of miscellaneous namespace.
`#^.`, `#^:` and `#^%` were chosen for the single, double and triple element grouping modifiers respectively because they have one, two and three circles/lines respectively
L

2023-03-09 13:43 UTC, Lyxal commented
Also, trigraphs are subject to change. If any of y'all feel like there's something more suitable for a Unicode, feel free to suggest it.

2023-03-09 14:07 UTC, Steffan153 commented
We should add tab completion to convert these to their unicode too. Except then maybe the `#` shouldn't be required.

2023-03-09 21:19 UTC, mathcat4 requested changes

2023-03-09 21:19 UTC, mathcat4 commented on shared/src/main/scala/SugarMap.scala
> +    val upperDowndot = "BDHILMNORST" -> "ḄḌḤỊḶṂṆỌṚṢṬ"
```suggestion
    val lowerUpdot = "abcdefghlmnoprstx" -> "ȧḃċḋėḟġḣŀṁṅȯṗṙṡṫẋ"
    val upperUpdot = "ABCDEFGHILMNOPRSTWX" -> "ȦḂĊḊĖḞĠḢİĿṀṄȮṖṘṠṪẆẊ"
    val upperDowndot = "BDHILMNORST" -> "ḄḌḤỊḶṂṆỌṚṢṬ"
```
well this doesn't seem right

2023-03-10 12:24 UTC, mathcat4 approved these changes

2023-03-10 12:25 UTC, merged