Remove html from cmc bit link and improve vyncoded cmc link formatting
Vyxal/Vyxal pull request #1739
Opened 2023-05-03 22:49 UTC by Lyxal

Needs linting and testing because I wrote it on mobile.

2023-05-03 23:43 UTC, Steffan153 commented
You clearly didn't test this

2023-05-03 23:44 UTC, Steffan153 commented on static/main.js
> +           break
```suggestion
            if (bytesLink.includes("bits") {
                bytesLink = `${len * 8} bits${bitver.value}, ${len} bytes`
            }
            output = `[Vyxal, ${bytesLink}${utfable ? '' : ' (UTF-8)'}: \`${code.replaceAll("`", "\\`")}\`](${url})` + (bytesLink.includes("bits") ? " ([vyncoded](https://github.com/Vyxal/Vyncode/blob/main/README.md)" : "")
            break
```

2023-05-04 15:25 UTC, nayakrujul approved these changes

2023-05-04 17:16 UTC, Steffan153 requested changes

2023-05-04 17:16 UTC, Steffan153 commented on static/main.js
> +            output = `[Vyxal, ${bytesLink}${utfable ? '' : ' (UTF-8)'}: \`${code.replaceAll("`", "\\`")}\`](${url})` + (bytesLink.includes("bits") ? " ([vyncoded](https://github.com/Vyxal/Vyncode/blo
```suggestion
            output = `[Vyxal, ${bytesLink}${utfable ? '' : ' (UTF-8)'}: \`${code.replaceAll("`", "\\`")}\`](${url})` + (bytesLink.includes("bits") ? " ([vyncoded](https://github.com/Vyxal/Vyncode/blob/main/README.md))" : "")
```

2023-05-04 17:56 UTC, merged