Create flags.md
Vyxal/Vyxal pull request #1972
Opened 2023-11-09 14:31 UTC by pacmanboss256

Add flags markdown file because they are only in the main.py for whatever reason

2023-11-09 23:43 UTC, Lyxal requested changes
Maybe this would be better suited as a table, rather than a bunch of `<h3>`s

2023-11-10 14:52 UTC, mathcat4 approved these changes

2023-11-10 14:52 UTC, mathcat4 commented on documents/knowledge/flags.md
> +
```suggestion

Use the `h` flag for a comprehensive list of available flags

```

2023-11-10 21:38 UTC, Lyxal approved these changes

2023-11-10 21:41 UTC, merged