Implement sensible `toString` for records, constructors and lambdas.
Vyxal/Vyxal pull request #2055
Opened 2024-01-10 11:27 UTC by RubenVerg

I noticed `AST`.`toVyxal` doesn't currently care about arity or explicit arguments, and I decided not to change that; if you want I can look into it (though I'm not sure how explicit arguments are currently implemented)

2024-01-10 11:33 UTC, ysthakur commented on shared/src/vyxal/VAny.scala
> +      case (name, (vis, value)) => s"$value ${vis match
I'd kinda prefer to have the match outside the string, assigned to a variable `prefix` or something

2024-01-10 11:44 UTC, lyxal requested changes
This only impacts when `toString` is called - printing a record doesn't call to string. This'll need to be changed.

2024-01-10 11:59 UTC, RubenVerg commented
@lyxal fixed, thanks for spotting that

2024-01-10 12:05 UTC, lyxal commented
For records, maybe something like:

```
<Name> { 
  !Public: value,
  $Restricted: value,
  =Private: value
}
```

For example,

```
<Map> {
  $keys: ["k1", "k2", "k3"],
  $values: ["v1", "v2", "v3"]
}
```

2024-01-10 12:14 UTC, RubenVerg commented
@lyxal with the newlines and indentation? that's gonna become an issue when there are maps nested inside maps, it's gonna look wrong

2024-01-10 12:15 UTC, lyxal commented
How about outermost map has indentation, and inner maps are flat

2024-01-10 15:04 UTC, ysthakur commented
I feel like we should either go all the way with flatness or all the way with indentation. Maybe `toString` could be completely flat, but when displaying in the REPL, we pretty-print everything (including lists?) with indentation? And in the web interpreter, it could show objects like the web console shows JS objects, with dropdowns and stuff

2024-01-11 11:25 UTC, lyxal approved these changes

2024-01-11 12:15 UTC, ysthakur commented on shared/src/vyxal/AST.scala
> +    this match
You could also make this a field by adding it to visibility,s constru tor

2024-01-11 16:40 UTC, ysthakur commented on shared/src/vyxal/AST.scala
> +    this match
```scala
enum Visibility(val sigil: String) derives CanEqual:
  case Public extends Visibility("!")
  case Private extends Visibility("=")
  case Restricted extends Visibility("$")
```

2024-01-11 19:35 UTC, ysthakur approved these changes
LGTM, this should make working in the REPL more pleasant. I was going to suggest changing the interpolated strings to not be multiline by extracting the expressions into variables, but tbh, it doesn't matter much

2024-01-11 19:35 UTC, merged