v3: Implement complex parts (∆ṗ) and polar parts (∆Ṗ)
Vyxal/Vyxal pull request #2103
Opened 2024-05-24 17:53 UTC by ysthakur

Implemented ∆ṗ for getting real and imaginary parts of a complex number and ∆Ṗ for getting polar coordinates of a complex number (radius and angle (radians))

2024-05-25 11:19 UTC, RubenVerg requested changes

2024-05-25 11:19 UTC, RubenVerg commented on shared/src/vyxal/Elements.scala
`VNum` has an `arg` method, no need to use atan2

2024-05-25 11:19 UTC, RubenVerg commented on shared/test/resources/tests.yaml
What does `W` next to the element name do?

2024-05-25 15:23 UTC, ysthakur commented on shared/test/resources/tests.yaml
It's to wrap the stack so we can check the real part/absolute value

2024-05-25 20:46 UTC, RubenVerg commented on shared/test/resources/tests.yaml
ah, i see. yeah i guess it makes sense, i don't think there's a better way with the way tests are structured

2024-05-25 22:04 UTC, ysthakur commented on shared/src/vyxal/Elements.scala
Ah nice, didn't see that

2024-05-26 01:50 UTC, lyxal approved these changes

2024-05-26 01:54 UTC, merged