Make stack a field of context
Vyxal/Vyxal pull request #266
Opened 2021-11-04 22:32 UTC by cgccuser

This is done so that `stack = asdf` works in transpiled code. Currently, it just seems to make a new local variable named `stack`.

2021-11-04 22:57 UTC, Lyxal requested changes
Use `ctx.stacks[-1]` instead.

2021-11-04 23:03 UTC, Lyxal commented
I also think that having `stack` as an attribute of `Context` would screw up local stacks for functions - defining a new stack for a function would overwrite the existing stack.

2021-11-04 23:03 UTC, Lyxal commented
Because I actually tried doing this once, only to realise it was a bad idea

2021-11-04 23:04 UTC, Lyxal commented
I don't exactly remember why I thought it was a bad idea, but I do know that it lead me to adding `stacks` as an attribute of `Context`

2021-11-04 23:22 UTC, cgccuser commented
@Lyxal The context isn't supposed to be kept the same across functions, a copy of it should be made so that the stack (and, if we ever choose to interpret Vyxal, variables) isn't overwritten.

2021-11-04 23:27 UTC, Lyxal commented
I thought context was supposed to be the same between all functions as a way of removing the need for globals

2021-11-04 23:33 UTC, cgccuser commented
Oh, what I had in mind for it was keeping track of different scopes using different Context objects. Would a custom `ctx.stack` getter/setter work?

2021-11-04 23:37 UTC, Lyxal commented
Why not just let python handle things with its default scoping? That way, you don't need to assign stack to context, as local stacks are contained within their own scope.

2021-11-04 23:39 UTC, cgccuser commented
Because with stuff like `W`, a new local variable called `stack` is created. That messes up the tests, and I'm pretty sure it'll mess things up in lambdas too.

2021-11-05 23:18 UTC, cgccuser commented
You know what, never mind, let's just continue using `stack` and change the tests or modify `W` in some hacky way to make it work.

2021-11-05 23:18 UTC, closed without merging