add "Number Stuff primitives from #160
Vyxal/Vyxal pull request #270
Opened 2021-11-11 13:40 UTC by razetime

Requires the equation one, which will be added soon. I'd like some verification on the other primitives i've added.

2021-11-11 22:50 UTC, Lyxal requested changes

2021-11-11 22:50 UTC, Lyxal commented on vyxal/helpers.py
> +    """Generate x digits of Pi. Spigot's formula."""
Don't forget to wrap this in a lazylist - pushing raw generators doesn't work. Also, this needs a context parameter if it's going to be used as an element function.

2021-11-11 22:50 UTC, Lyxal commented on vyxal/elements.py
> +    """
This should be made to vectorise over lists, which can be done by checking if `vy_type(lhs, simple=True) is list`

2021-11-11 22:50 UTC, Lyxal commented on vyxal/elements.py
> +    """
Same thing about vectorising

2021-11-12 03:10 UTC, Lyxal requested changes

2021-11-12 03:10 UTC, Lyxal commented on vyxal/helpers.py
> +def pi_digits(x: int):
`def pi_digits(x: int, ctx: Context)`

2021-11-12 03:10 UTC, Lyxal commented on vyxal/elements.py
> +    "∆I": process_element(lambda lhs, ctx: pi_digits(lhs), 1),
`"∆I": process_element(pi_digits, 1),`

2021-11-12 03:14 UTC, razetime commented on vyxal/helpers.py
> +def pi_digits(x: int):
fixed this thing

2021-11-12 03:15 UTC, Lyxal approved these changes

2021-11-12 03:15 UTC, merged