Remove unnecessary ctx argument to strip in P aka strip
Vyxal/Vyxal pull request #347
Opened 2021-12-06 23:29 UTC by cgccuser

2021-12-06 23:33 UTC, Lyxal approved these changes

2021-12-07 03:56 UTC, chunkybanana commented on vyxal/elements.py
> -        (NUMBER_TYPE, str): lambda: vy_eval(vy_str(lhs).strip(rhs), ctx),
This one looks like it should stay as it's inside the call to `vy_eval`

2021-12-07 03:57 UTC, chunkybanana requested changes
One of these looks like it should stay, as it's in a Vyxal function

2021-12-07 22:59 UTC, Lyxal requested changes
I agree with EmanresuA

2021-12-08 00:18 UTC, cgccuser commented
Whoops

2021-12-08 00:32 UTC, Lyxal approved these changes
Lgtm

2021-12-08 04:17 UTC, chunkybanana approved these changes

2021-12-08 04:17 UTC, merged