Generate tests in the test workflow
Vyxal/Vyxal pull request #533
Opened 2021-12-28 23:34 UTC by cgccuser

I just realized I made a mistake in elements.yml but it wasn't noticed because the tests weren't regenerated, which is not good.

2021-12-28 23:53 UTC, pxeger commented
I think we should add a separate CI check to ensure this file (and the others generated from `elements.yaml`) get regenerated? I think that could be done with https://pre-commit.ci pretty easily.

But this is a good step for now

2021-12-28 23:53 UTC, pxeger approved these changes

2021-12-28 23:54 UTC, pxeger commented
No squash please

2021-12-28 23:56 UTC, cgccuser commented
Why no squash?

2021-12-28 23:57 UTC, pxeger commented
~~Badminton's just better~~

Because it obscures commit history which carries useful information.

2021-12-28 23:57 UTC, pxeger requested changes
This needs to install `yaml` first

2021-12-28 23:59 UTC, Lyxal approved these changes
Maybe also add something later for documentation rerolling

2021-12-29 00:00 UTC, cgccuser commented
Sounds good, although generating documentation should go in its own workflow.

2021-12-29 00:00 UTC, pxeger requested changes

2021-12-29 00:00 UTC, pxeger commented on .github/workflows/run-tests.yaml
>          python -m pip install poetry
```suggestion
        python -m pip install poetry yaml
```

2021-12-29 00:04 UTC, cgccuser commented
There are so many commits that at this point we might as well squash them or make a new branch and add those in manually.

2021-12-29 03:14 UTC, pxeger approved these changes

2021-12-29 03:14 UTC, pxeger commented
I still don't like squashing, but whatever

2021-12-29 03:16 UTC, cgccuser commented
I mean, we could make a new branch and add those commits in again.

2021-12-29 03:18 UTC, cgccuser commented
You know what, I'm too lazy to do that, so here we go. And fwiw, tennis > badminton.

2021-12-29 03:18 UTC, merged