hopefully this makes W a little better
Vyxal/Vyxal pull request #634
Opened 2022-01-19 04:36 UTC by Lyxal

2022-01-19 11:58 UTC, razetime approved these changes

2022-01-19 17:51 UTC, pxeger approved these changes
I mean if it works, then fine, but this does not need to be this complicated

2022-01-19 17:51 UTC, pxeger commented on vyxal/elements.py
> +        "stack.append(temp); print(stack)",
Way simpler:
```suggestion
        "stack[:] = [deep_copy(stack)]"
```

2022-01-19 22:16 UTC, cgccuser approved these changes

2022-01-19 22:17 UTC, cgccuser requested changes

2022-01-19 22:17 UTC, cgccuser commented on vyxal/elements.py
> +        "stack[:] = [deep_copy(stack)]"
```suggestion
        "stack[:] = [deep_copy(stack)]",
```

2022-01-19 22:18 UTC, cgccuser commented
Boy this PR turned into a mess...

2022-01-19 22:18 UTC, cgccuser approved these changes

2022-01-19 22:20 UTC, cgccuser commented
Okay imma just check it out locally and use `stack[:] = [stack[:]]` or something

2022-01-20 00:54 UTC, cgccuser commented on vyxal/elements.py
> +        "stack[:] = [deep_copy(stack)]",
```suggestion
        "temp = list(deep_copy(stack))\n"
        "pop(stack, len(stack), ctx)\n"
        "stack.append(temp); print(stack)",
```

2022-01-20 00:57 UTC, merged