Add apply lambda
Vyxal/Vyxal pull request #723
Opened 2022-02-08 11:37 UTC by Lyxal

Provides somewhat of a fix to #336. I've had this in mind for 2 months now.

2022-02-08 12:26 UTC, cgccuser requested changes
Minor changes but this is as good as approved

2022-02-08 12:26 UTC, cgccuser commented on documents/knowledge/elements.yaml
> +  name: Apply Lambda
Poggers, might want to also call it foreach

2022-02-08 12:26 UTC, cgccuser commented on documents/knowledge/elements.yaml
> +  description: Like a mapping lambda, but the results are evaluated immediantly, instead of being lazily evaluated
Immediately

2022-02-09 00:28 UTC, cgccuser approved these changes

2022-02-10 04:36 UTC, PyGamer0 approved these changes
ok

2022-02-10 04:36 UTC, merged