Add documentation for the probably unknown feature of function multiplication
Vyxal/Vyxal pull request #752
Opened 2022-02-28 11:35 UTC by Lyxal

2022-02-28 12:01 UTC, SE-Nitro approved these changes

2022-02-28 16:09 UTC, AMiller42 commented
> Who knew this stuff existed 🤔

Me, only because I know *way* too much about Vyxal and its quirks.

2022-02-28 16:54 UTC, pxeger commented on documents/knowledge/elements.yaml
> +  description: Get indices of truthy elements or make the arity of a function 3
This now loses the description for numbers, which is normal tripling

2022-02-28 16:55 UTC, pxeger requested changes

2022-02-28 16:55 UTC, pxeger commented on documents/knowledge/elements.yaml
> +  description: Get indices of truthy elements or make the arity of a function 3
This now loses the description for numbers, which is normal tripling

2022-02-28 22:55 UTC, cgccuser requested changes
Based on pxeger's comment

2022-02-28 22:55 UTC, cgccuser commented on documents/knowledge/elements.yaml
> +  description: Get indices of truthy elements or make the arity of a function 3
```suggestion
  name: Truthy Indices / Triple / Triadify
  description: Get indices of truthy elements, triple, or make the arity of a function 3
```

2022-02-28 22:57 UTC, merged

2022-03-02 07:46 UTC, pxeger commented
> Screw that guy

hey >:(