Add distance matrix elements
Vyxal/Vyxal pull request #848
Opened 2022-04-13 14:50 UTC by cgccuser

`Þd` for distance of directed matrices and `Þw` for distance of undirected matrices. We need a better symbol for the second one, though.

2022-04-13 14:53 UTC, cgccuser commented
Wait, how are the tests passing now? All the bitwise stuff fails on my computer.

2022-04-13 23:12 UTC, AMiller42 requested changes

2022-04-13 23:12 UTC, AMiller42 commented on documents/knowledge/elements.yaml
> +    lst: Dstance matrix
Lines 4870 and 4880 have "Distance" misspelled.

2022-04-14 03:36 UTC, chunkybanana approved these changes
Fix the typos tho

2022-04-14 13:46 UTC, merged