Add the string overload of ṅ to the YAML
Vyxal/Vyxal pull request #925
Opened 2022-05-06 13:18 UTC by Lyxal

Closes #917

2022-05-06 15:28 UTC, Steffan153 requested changes

2022-05-06 15:28 UTC, Steffan153 commented on documents/knowledge/elements.yaml
> +      lst: "".join(a)
You need to escape the quotation marks here, it's invalid YAML. That's what's making the CIs fail.

```suggestion
      lst: \"\".join(a)
```

2022-05-06 15:36 UTC, Steffan153 commented
well that didnt work. now it shows the backslashes in the txt and md as well

2022-05-06 15:37 UTC, Steffan153 commented on documents/knowledge/elements.yaml
> +      lst: \"\".join(a)
do this be work
```suggestion
      lst: '"".join(a)'
```

2022-05-06 15:38 UTC, Steffan153 approved these changes

2022-05-07 15:34 UTC, cgccuser approved these changes

2022-05-07 15:35 UTC, merged